### ISSUE TITLE
problem own calendar server

### ISSUE THREAD

**Issue by salberch** [opentimestamps/opentimestamps-server#16]
We are trying to start calendar server in regtest mode, but there is an error:

./otsd --btc-regtest --btc-min-confirmations 1 --btc-min-tx-interval 60
Opening journal for appending...
Journal has 2 entries
Starting aggregator loop
Starting stamper loop
New block 358b81119a13ba553a3f178601e466e2eab5255cd5b542b4e611ecc28c45a420 at height 109
Sent timestamp tx 2da1295f2399153b17c81bcd15f313b64f16eb112dd7386b0ad6f105448a20c8; 2 total commitments

127.0.0.1 - - [12/Jul/2017 01:12:10] "GET / HTTP/1.0" 200 -
Aggregated 1 digests under commitment 1cb33f719e10fb673e78cd80055b002470da8d683cb95bdcc6afacc3b981736b
127.0.0.1 - - [12/Jul/2017 01:12:33] "POST /digest HTTP/1.0" 200 -
127.0.0.1 - - [12/Jul/2017 01:12:47] "GET /timestamp/596577811cb33f719e10fb673e78cd80055b002470da8d683cb95bdcc6afacc3b981736ba6a18d8036965fd0 HTTP/1.0" 404 -
New block 163b023c6b1f2d9f1be525d5a2c4af731b8fad5cd94fdefd3fe4f72f1dfd62cb at height 110
New block 26917fba243ba1e01bc2916b431657c0ce5d2de64e7e3d404b76843d4fd50c5c at height 111
New block 52c962c801c28979a3512310ae27489d358f269b4d4f0576b3f7510b02f9a001 at height 112
Sent timestamp tx 76fb610c7992a55a9b7ff0caa5f9fdfc0994b82bcf6b4775ec017060d571c312, replacing 2da1295f2399153b17c81bcd15f313b64f16eb112dd7386b0ad6f105448a20c8; 3 total commitments
New block 08ecdf6a822216352601aef1ef948434379bf5214fb28d68cd9fcf44eedf5642 at height 113
__do_bitcoin() failed: AssertionError()

**Comment by salberch** [comment]
The unit tests fail:

======================================================================
ERROR: test_blobs (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git blob hashing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 46, in test_blobs
    stamper = self.make_stamper("53c68bc976c581636b84c82fe814fab178adf8a6")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_dangling_symlink (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with dangling symlink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 144, in test_dangling_symlink
    stamper = self.make_stamper("a59620c107a67c4b6323e6e96aed9929d6a89618")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_empty_tree (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with a single empty file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 66, in test_empty_tree
    stamper = self.make_stamper("30f6c357d578e0921dc6fffd67e2af1ce1ca0ff2")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_huge_tree (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Really big git tree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 153, in test_huge_tree
    stamper = self.make_stamper("a52fe6e3d4b15057ff41df0509dd302bc5863c29")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_submodule (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 137, in test_submodule
    stamper = self.make_stamper("a3efe73f270866bc8d8f6ce01d22c02f14b21a1a")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_tree_with_children (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with child trees
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 104, in test_tree_with_children
    stamper = self.make_stamper("b22192fffb9aad27eb57986e7fe89f8047340346")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_tree_with_prefix_matching_blob (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with prefix matching blob
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 131, in test_tree_with_prefix_matching_blob
    stamper = self.make_stamper("75736a2524c624c1a08a574938686f83de5a8a86")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

======================================================================
ERROR: test_two_file_tree (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git tree with a two files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 82, in test_two_file_tree
    stamper = self.make_stamper("78eb5cdc1ec638be72d6fb7a38c4d24f2be5d081")
  File "/usr/src/opentimestamps-server-master/opentimestamps/tests/core/test_git.py", line 36, in make_stamper
    repo = git.Repo(__file__ + '../../../../../')
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /usr/src/opentimestamps-server-master

----------------------------------------------------------------------
Ran 69 tests in 9.728s

**Comment by petertodd** [comment]
Weird!

Can you tell us what python version your using, and what OS/distribution?

**Comment by franruiz** [comment]
Peter,
Thank you for your answer. I'm working too with @salberch trying to get this working. 

We are using:
Ubuntu 16.04.1 LTS & Python 3.5.2

Are those versions OK ?

**Comment by RCasatta** [comment]
I notice test errors are always on test_git.py, I had similar error on the travis build cause they are using the depth option by default, downloading only the last 50 commit. Many tests on test_git.py rely on early commit inside the repo itself. On Travis I solved by adding --depth=9999999 option on command line which override the default

**Comment by petertodd** [comment]
@franruiz Those versions look ok.

The git-related errors suggest you installed it via a tarball, correct?
