### ISSUE TITLE
Tests error on Mac OS X

### ISSUE THREAD

**Issue by RCasatta** [opentimestamps/opentimestamps-server#8]
running `python3 -m unittest discover -v` on Mac OS X gives the following error

```
======================================================================
ERROR: test_blobs (opentimestamps.tests.core.test_git.Test_GitTreeTimestamper)
Git blob hashing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xxx/github/opentimestamps/opentimestamps-server/opentimestamps/tests/core/test_git.py", line 58, in test_blobs
    stamper = self.make_stamper("30f6c357d578e0921dc6fffd67e2af1ce1ca0ff2")
  File "/Users/xxx/github/opentimestamps/opentimestamps-server/opentimestamps/tests/core/test_git.py", line 37, in make_stamper
    db = dbm.open(self.db_dir.name + '/db', 'c')
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 35] Resource temporarily unavailable

----------------------------------------------------------------------
```

looks a known bug of dbm on the platform

**Comment by petertodd** [comment]
When you say known bug, got a link talking about it?

**Comment by RCasatta** [comment]
i was referring to this http://stackoverflow.com/questions/37354619/dbm-35-resource-temporarily-unavailable-on-osx-python-2-7

**Comment by petertodd** [comment]
Great, thanks!
