### ISSUE TITLE
Sent timestamp tx, then stuck at Can't timestamp; no spendable outputs

### ISSUE THREAD

**Issue by insidenothing** [opentimestamps/opentimestamps-server#81]
Server Running at https://legaltimestamp.com/ 

**ok it worked but i forgot to unlock wallet first**

2021-02-08 12:49:50,259 Opening journal for appending...
2021-02-08 12:49:50,259 Journal has 1 entries
2021-02-08 12:49:50,263 Starting aggregator loop
2021-02-08 12:49:50,263 Starting stamper loop
2021-02-08 12:49:50,271 New block 00000000000000000009371acf1b0f4a79b854962d2e1ddef818fd4a513ae251 at height 669693
2021-02-08 12:49:50,780 Sent timestamp tx b3303a1a76baa2513863f0bee4bec74d7223a2daa43c0f5d762ff0ca3bf24e5c; 1 total commitments
2021-02-08 12:53:05,058 New block 00000000000000000002664dd7f9dd0126191d7d8de9d32d4ac4a3b2fe2401e0 at height 669694
2021-02-08 12:53:05,569 __do_bitcoin() failed: JSONRPCError({'code': -13, 'message': 'Error: Please enter the wallet passphrase with walletpassphrase first.'})
Traceback (most recent call last):
  File "/home/ec2-user/opentimestamps-server/otsserver/stamper.py", line 490, in __loop
    self.__do_bitcoin()
  File "/home/ec2-user/opentimestamps-server/otsserver/stamper.py", line 425, in __do_bitcoin
    r = proxy.signrawtransaction(unsigned_tx)
  File "/usr/local/lib/python3.7/site-packages/bitcoin/rpc.py", line 708, in signrawtransaction
    r = self._call('signrawtransaction', hextx, *args)
  File "/usr/local/lib/python3.7/site-packages/bitcoin/rpc.py", line 238, in _call
    raise JSONRPCError(response['error'])
bitcoin.rpc.JSONRPCError: {'code': -13, 'message': 'Error: Please enter the wallet passphrase with walletpassphrase first.'}

**now no matter what i do it**

2021-02-08 14:08:26,683 Opening journal for appending...
2021-02-08 14:08:26,683 Journal has 1 entries
2021-02-08 14:08:26,687 Starting aggregator loop
2021-02-08 14:08:26,690 Starting stamper loop
2021-02-08 14:08:26,699 New block 00000000000000000009369a02cd2ca038d8a3fb94398b6648fda8ddc3e4e24c at height 669705
2021-02-08 14:08:27,150 Couldn't find a confirmed output, trying unconfirmed
2021-02-08 14:08:27,190 Can't timestamp; no spendable outputs

**restart bitcoin node and otsd**

[ec2-user@ip-172-31-61-7 ~]$ bitcoin-cli getwalletinfo
{
  "walletname": "",
  "walletversion": 169900,
  "balance": 0.00030304,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 2,
  "keypoololdest": 1612119205,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "unlocked_until": 0,
  "paytxfee": 0.00000000,
  "hdseedid": "c86cfb653b5db71d1c566329736e744af91cfd15",
  "hdmasterkeyid": "c86cfb653b5db71d1c566329736e744af91cfd15",
  "private_keys_enabled": true
}

**unlock wallet for a year**

[ec2-user@ip-172-31-61-7 ~]$ bitcoin-cli walletpassphrase [password] 31556952
[ec2-user@ip-172-31-61-7 ~]$ bitcoin-cli getwalletinfo
{
  "walletname": "",
  "walletversion": 169900,
  "balance": 0.00030304,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 2,
  "keypoololdest": 1612119205,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "unlocked_until": 1644350490,
  "paytxfee": 0.00000000,
  "hdseedid": "c86cfb653b5db71d1c566329736e744af91cfd15",
  "hdmasterkeyid": "c86cfb653b5db71d1c566329736e744af91cfd15",
  "private_keys_enabled": true
}
2021-02-08 14:13:37,975 Opening journal for appending...
2021-02-08 14:13:37,976 Journal has 1 entries
2021-02-08 14:13:37,980 Starting aggregator loop
2021-02-08 14:13:37,980 Starting stamper loop
2021-02-08 14:13:37,987 New block 00000000000000000009cf1b219efe88e23014808b2714fd2e185eb240397948 at height 669707
2021-02-08 14:13:38,279 Couldn't find a confirmed output, trying unconfirmed
2021-02-08 14:13:38,300 Can't timestamp; no spendable outputs

**any ideas how to get back on track? do i need more btc ?**

**Comment by insidenothing** [comment]
**could it be related to** 
--btc-min-confirmations N
                        Confirmations required before we save a Bitcoin
                        timestamp permanently, must be greater than 1
                        (default: 6)
**or** 
--btc-max-fee FEE     Maximum transaction fee (default: 0.001 BTC)

**Comment by insidenothing** [comment]
![Screenshot_20210208-103110_Chrome](https://user-images.githubusercontent.com/356752/107241742-462c1780-69f9-11eb-8d0b-6abbcd761d3b.jpg)

**Comment by insidenothing** [comment]
[ec2-user@ip-172-31-61-7 opentimestamps-server]$ bitcoin-cli listtransactions
[
  {
    "account": "",
    "address": "bc1q3u6cuasklgh6vq3hhwmfkjd3ay0mv0wwml6uy3",
    "category": "receive",
    "amount": 0.00030486,
    "label": "",
    "vout": 91,
    "confirmations": 1204,
    "blockhash": "000000000000000000003341c3916ebd55bb5cfdc53954ae6a6c29fdccdba102",
    "blockindex": 662,
    "blocktime": 1612121523,
    "txid": "1ccd1c1ba947cca6347d6074ec0620e3ccf5b85fdfd7d5be1df52c6c9ce84bfa",
    "walletconflicts": [
    ],
    "time": 1612121523,
    "timereceived": 1612732901,
    "bip125-replaceable": "no"
  },
  {
    "account": "",
    "address": "bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj",
    "category": "receive",
    "amount": 0.00030304,
    "label": "",
    "vout": 0,
    "confirmations": 0,
    "trusted": true,
    "txid": "b3303a1a76baa2513863f0bee4bec74d7223a2daa43c0f5d762ff0ca3bf24e5c",
    "walletconflicts": [
    ],
    "time": 1612788577,
    "timereceived": 1612788577,
    "bip125-replaceable": "yes"
  },
  {
    "account": "",
    "category": "send",
    "amount": 0.00000000,
    "vout": 1,
    "fee": -0.00000182,
    "confirmations": 0,
    "trusted": true,
    "txid": "b3303a1a76baa2513863f0bee4bec74d7223a2daa43c0f5d762ff0ca3bf24e5c",
    "walletconflicts": [
    ],
    "time": 1612788577,
    "timereceived": 1612788577,
    "bip125-replaceable": "yes",
    "abandoned": false
  },
  {
    "account": "",
    "address": "bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj",
    "category": "send",
    "amount": -0.00030304,
    "label": "",
    "vout": 0,
    "fee": -0.00000182,
    "confirmations": 0,
    "trusted": true,
    "txid": "b3303a1a76baa2513863f0bee4bec74d7223a2daa43c0f5d762ff0ca3bf24e5c",
    "walletconflicts": [
    ],
    "time": 1612788577,
    "timereceived": 1612788577,
    "bip125-replaceable": "yes",
    "abandoned": false
  }
]

**Comment by insidenothing** [comment]
am i hung up on https://www.blockchain.com/btc/address/bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj getting confirmed? Like nothing is wrong, i just need to wait?

**Comment by insidenothing** [comment]
**Sigh, this can't be right?** 
[ec2-user@ip-172-31-61-7 opentimestamps-server]$ bitcoin-cli getaddressesbyaccount ""
[
  "bc1qqc7cjm72e6842znycyja93yyfq8w9km2g3addk",
  "bc1qp8pwnvrv7d4kvew4p3kcfw438qyvuaz5gn68ps",
  "bc1qpjzwvf8ty3mvukuqelyrvmm028skslnlhlt7ag",
  "bc1qzwy4cd0pktllqs57963364ju0amee98t5zylk0",
  "bc1qrgqruse9zwrhmtfntnjrehvg3p40kmep8kmryp",
  "bc1qrdkmq0dm07v9r86mge9r3n7a8jqhsaqgznsewk",
  "bc1qr5eug20qnxuksexk3ggl0k43gwvz259jkfxjyx",
  "bc1qygdvxg8qrem6jxksqq8yeuncaww8sg92zmuve6",
  "bc1qylwdpcxehpyeesl0zm7s7vdw5q2xzpk40nr52v",
  "bc1q9fg8je5vr69p72xlvu3z7743wf5c55xrm4tdst",
  "bc1q9wfkjdfn2093a4tcd6c9ce2xl0k4y9rzvn6ka3",
  "bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj",
  "bc1q9k57fxujnnu3hlcu7hwc2wfpx8rrx8frpdz04f",
  "bc1q9h40cmehfme9gj0579aprm2ghjegx8k0rlw8xx",
  "bc1qxpqadh2nzzhvgg7ggg79lfhe54lttl6ueezunk",
  "bc1qxpmydkpcgxz75cswlrqxylr2xvl9e8tjjwxcmx",
  "bc1qxx9679lddycqywdrp8550jmzlfq78e5phr22ga",
  "bc1qx8uff75s4xfsnc8gmwdzh3q345xvm2jg0phjcf",
  "bc1qxv5jdltezkpcfjfe20ejzrdfe5y00e7fenna3l",
  "bc1qx4a6wnm2t0g0wp97kvl3k7a9mer2wjyjwj0jyc",
  "bc1qxkd73mhmekqx8vp8cu9jjjqwkc8vft9sx3l5mh",
  "bc1q8pfd202d40kuc9p2rhss4vu4gzdrsry3yecgj7",
  "bc1q8yhahvvzdnaxpvzs4setxkh32df5hfxs0mfkl0",
  "bc1q8vjn4hs0c6v6xdapf703s6007crygdef7lycvv",
  "bc1q8wgu5zwtkf63s7vpsqjg4du2pa2fsuhz4cf4sd",
  "bc1q8ey4qgen0whd6g8gsa035gy8wquxqxu0mhgxgx",
  "bc1qgulxmuukzk8yyrq8jdhsqryud3f3592xthdgsk",
  "bc1qfzjg4g3qeypyj2l8hue4pkvaug5pskdd8amgkf",
  "bc1qfdczfv0kdlx9re6pu8n4xtd3umg7pmgpsjc6q5",
  "bc1qfww458lmp3aslcnua5lj787kp56w66f6glzcgz",
  "bc1qf3u7tvq0r94qvwlsqrr87ep6799x6345qggz5c",
  "bc1qf6wruzu7kyq5zzjv08kj0yfd75za9sfwpfr0vg",
  "bc1q28qdage6enw32q5pqtgtlrhntvjwdxj94ne27v",
  "bc1q28dswmkshd3yx4g6hs57zcfqqvjx7gmeq2ne6x",
  "bc1q2nzjpqw6ngkgq05syp9gslmgznn4ntnrtsn5u7",
  "bc1q2k5qzjdz4tlm3hh4hqequsxvqkn9y0j44lwm6y",
  "bc1qtptwa2zgavxxvczl7xlq3vg8h7899lhs83phkc",
  "bc1qtw4cu837e9gpz2uwe837urssfnmq8r43qrdkqm",
  "bc1qtntxxty4r6qfukkgmwy26qqu9n7c2x0nuttxrk",
  "bc1qtn66furztzwa86qqcmjkny7kt8a453du3auw2l",
  "bc1qvqwtuxmht52vpjs0g96udm693cndsr8w2y86lu",
  "bc1qvufkcfnddsrl38cfrj9lm3kakldn08qxdy9njn",
  "bc1qdx3fpvsf9sm854z70ys4u5wncymqsfxf8e47uy",
  "bc1qdttl8gwk6qf28vmf97wpqd0nu2ylr32sze08cs",
  "bc1qds03megecv9jz6v4qe53v3wqx6hpx5502fjz5q",
  "bc1qdc8nq44ardgcpv7lyprk8al0l3psjlyxx053g5",
  "bc1qwykjgcsa88qtglajru6ttm8ds9urs9ruaxjj42",
  "bc1qww7n0g5gwezygyy0k7k6ez6u2g7498xeurfarf",
  "bc1q0egec4q8zm884wqe3660asw4y6xlc5g5qnqjh5",
  "bc1qs50z80mkfndfjkyzdf3xywuscfxdm2z76e57l6",
  "bc1q39cdwpu7c7f33mvup6h7wrcedh2cm3e3cjkjg4",
  "bc1q3wnrux6lk822hzkm30a6gjuvpe5ef0gymm759m",
  "bc1q33jdmwug6dycskysala3wrwura54xenhxjwfjv",
  "bc1q3jz6cjg8p7xh6vw7079m2nmyqujn78yq803njr",
  "bc1q365u5m0nwu2aj7rlupgxyvs9ax3qtdrpcjrcy0",
  "bc1q3u6cuasklgh6vq3hhwmfkjd3ay0mv0wwml6uy3",
  "bc1qjze43llwzx5uxady4t2c93net7hzachfepq5e4",
  "bc1qjx2c7k9ftpkdph8hxqanvcuzfzj557jsnnp3yy",
  "bc1qj8mtu6lhp9t45q8dd2fegwmv88u0fvlq5ut57d",
  "bc1qjwqkv25kulcdqd2jlxmkpz2p34gujl69h50jy0",
  "bc1qjum2g7h6kvqm9n38eup2mdry9m6wej8qs7m5j3",
  "bc1qny0hqympewggyvlkslmcss0jxsjk52cdyreqcy",
  "bc1qntkzxdhrqdr56ext44vhkkv5p6h2hnees54rfe",
  "bc1qnv5y5ujlc7zwkgtgpraur960usyzu5tmds74kg",
  "bc1qn3qh2zgzy7p6xvhddkd44jrfdv6n8az0erdlr9",
  "bc1qna8ckxg4d5fns9tgxury0rrrtafl0clt2lktn3",
  "bc1q5g5axd75gmd3403f33uqs4mxmu7349j5rjtxqu",
  "bc1q5vc30juhexgndxw9k8njvqk208mjk2ycg2nq0f",
  "bc1q483vnh4aalgvtusqanz6xtdj6ef48p08vgq36m",
  "bc1q4gehqs2ru74vhu6l5lnp7f93j64slfgl03na99",
  "bc1q4ckhvy8y7jgclfk4g92ndg3vaflf2nt784gxrr",
  "bc1q4egjpg0v6tcf9u5fnthxuylqk7h9ghrgwfwj7y",
  "bc1qk8ge9dn93v4ncu8cxth2ve0guuk79l4ewk63n2",
  "bc1qhr0ylura8ueajfc0sa7dgwh6fdavgtxe6xjlgv",
  "bc1qhd7nm0zlf5vg5c2hfze5v4a7358wvavdn3tfpa",
  "bc1qhuda82pyhuec4f36gy6p65dngmg9yyd0h8hldn",
  "bc1qhaf990vgc5rrmu5p6wsqv834f45ryds778dpwy",
  "bc1qcqc2gr8mljcqjfxaslnp58lgkwepkce04cnfac",
  "bc1qcpj02qvz9jxn9zpvtga46ukhvxesshdr7jd262",
  "bc1qcruyadvqllenrqhu2s7cfcz3t87easurgwzaxp",
  "bc1qc5w63037z7lqqtkfvcj9vd2emvl2wtwurfzpv3",
  "bc1qcc9qwt0c8y2c34jll9pqk9ghhn8nccp9nm8k7t",
  "bc1qccs6kh7j2rnk3aer54c6hutzh32scsw363axkp",
  "bc1qcmmt3778r0v9yeapwt5vrz6kf08dx44rctz9s2",
  "bc1qetrsmj2etvhah78ulre2ppvdrgv7rwsn2kw5p7",
  "bc1qeje9ruetdrefchn69f65clr6phq928rys3r6mh",
  "bc1q6tkgsggmyjze95wprps3dtpckpcvu4knwdy5wp",
  "bc1q6hgm68kwlkcykz4entjfq92rsg409l0gr4knkv",
  "bc1qm83kldtvvm7y8dw83dm0ts2p6d5jhccwdtft4j",
  "bc1qmwk3r3mrxeqmcdwfv9tgt6ecfdvt9fq63rjsp4",
  "bc1qmkr5km5cwuvykv3esscc4ptzjgl6ep2kujf2cq",
  "bc1qu0xwk47gx5hwy6z6jjhyflfydggvmpqryx9f3y",
  "bc1qay0lgnu4s26jm3tx5x5delk8gzx6us6uk4jqwy",
  "bc1qa9x63pu7tfh0fw20ye85slzyl5kfnk6mmq678q",
  "bc1qa4kq8s657l4ldknp2f662zfujlukg4phu9xl9v",
  "bc1qalte83k8dgzmuc47x52ahamhxqfth03w5tvc7w",
  "bc1q7rtzgdaxwg77qm89jr6g0huhnuzg8th7v8psxv",
  "bc1q7y005dxwuj44l9ahhyd8gv9xz7vp4gkyemxkyj",
  "bc1q75s6xm7gg30695fjs3wfr0jlp2ge6p4ved4g7w",
  "bc1q76ng5war3c9qrjyx3fj3sa49fqrhfh23gwh0gq",
  "bc1q7u74hkt8tp39yqpfkj56y7fqsxawlsn3lpamlr",
  "bc1qlaq6j9zr3c3evtv2ckc7wzex60eft6qvu6j0tp"
]
[ec2-user@ip-172-31-61-7 opentimestamps-server]$ bitcoin-cli getaddressesbyaccount "" | grep bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj
  "bc1q9nuj630htrhx0ejgwd8j7qfrgn6jnth8q0dxvj",
[ec2-user@ip-172-31-61-7 opentimestamps-server]$

**Comment by insidenothing** [comment]
1. switched to full node
2. add abt $100 btc
3. bitcoin-cli generate 10

**2021-02-13 16:01:19,921 Success! 2 commitments timestamped, now waiting for 5 more confirmations**
